// AUTOGENERATED FROM Scripts/generate-textures.sh

using System.Collections.Generic;

namespace AstroMiner.Definitions
{
    public static class Tx
    {
        public const string Cracks = "Cracks";
        public const string DirectionalLight = "DirectionalLight";
        public const string DogicaFont = "DogicaFont";
        public const string Door = "Door";
        public const string Dynamite = "Dynamite";
        public const string Explosion = "Explosion";
        public const string GrappleIcon = "GrappleIcon";
        public const string Icons = "Icons";
        public const string KrevikDocks = "KrevikDocks";
        public const string LaunchConsole = "LaunchConsole";
        public const string Lava = "Lava";
        public const string MountainsNiceTiled = "MountainsNiceTiled";
        public const string Player = "Player";
        public const string RadialLight = "RadialLight";
        public const string Ship = "Ship";
        public const string ShipShadowMap = "ShipShadowMap";
        public const string Star = "Star";
        public const string Tileset = "Tileset";
        public const string White = "White";
        public static class Backgrounds
        {
            public const string Oizus = "Backgrounds/Oizus";
            public const string OizusClouds = "Backgrounds/OizusClouds";
            public const string OizusClouds1 = "Backgrounds/OizusClouds1";
            public const string OizusClouds2 = "Backgrounds/OizusClouds2";
        }
        public static class Miner
        {
            public const string MinerNoTracks = "Miner/MinerNoTracks";
            public const string Tracks0 = "Miner/Tracks0";
            public const string Tracks1 = "Miner/Tracks1";
            public const string Tracks2 = "Miner/Tracks2";
        }

        public static readonly List<string> AllTextures = new List<string>
        {
            "Cracks",
            "DirectionalLight",
            "DogicaFont",
            "Door",
            "Dynamite",
            "Explosion",
            "GrappleIcon",
            "Icons",
            "KrevikDocks",
            "LaunchConsole",
            "Lava",
            "MountainsNiceTiled",
            "Player",
            "RadialLight",
            "Ship",
            "ShipShadowMap",
            "Star",
            "Tileset",
            "White",
            "Backgrounds/Oizus",
            "Backgrounds/OizusClouds",
            "Backgrounds/OizusClouds1",
            "Backgrounds/OizusClouds2",
            "Miner/MinerNoTracks",
            "Miner/Tracks0",
            "Miner/Tracks1",
            "Miner/Tracks2",
        };
    }
}
