#!/bin/bash

# Generates AstroMiner/Definitions/Tx.cs with string constants for all PNG files in the Content/img directory.
# Also generates AstroMiner/Content/Content.mgcb with texture build configuration.
# Run from the project root: ./Scripts/generate-textures.sh

# Configuration
sourceDirectory="AstroMiner/Content/img"
txDestinationPath="AstroMiner/Definitions/Tx.cs"
mgcbDestinationPath="AstroMiner/Content/Content.mgcb"

# Function to convert filename to property name (remove extension)
to_property_name() {
    local filename="$1"
    echo "${filename%.*}"
}

# Function to validate filename format
validate_filename() {
    local filename="$1"
    local basename_no_ext="${filename%.*}"
    
    # Check if filename starts with capital letter and only contains letters, numbers, underscores
    if [[ ! "$basename_no_ext" =~ ^[A-Z][A-Za-z0-9_]*$ ]]; then
        echo "ERROR: Invalid filename format '$filename'. Filenames must start with a capital letter and only contain letters, numbers, or underscores." >&2
        return 1
    fi
    return 0
}

# Function to validate all files in a directory recursively
validate_all_files() {
    local dir="$1"
    local has_errors=0
    
    # Check for non-PNG files
    for file in "$dir"/*; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        
        # Skip if it's a PNG file (we'll validate PNG filenames separately)
        if [[ "$filename" == *.png ]]; then
            continue
        fi
        
        echo "ERROR: Non-PNG file found: $file" >&2
        has_errors=1
    done
    
    # Validate PNG filenames
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        
        if ! validate_filename "$filename"; then
            has_errors=1
        fi
    done
    
    # Process subdirectories recursively
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        if ! validate_all_files "$subdir"; then
            has_errors=1
        fi
    done
    
    return $has_errors
}

# Function to generate class content recursively
generate_class_content() {
    local dir="$1"
    local indent="$2"
    local relative_path="$3"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        echo "${indent}public const string $property_name = \"$file_path\";"
    done
    
    # Process subdirectories
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        
        echo "${indent}public static class $dirname"
        echo "${indent}{"
        generate_class_content "$subdir" "$indent    " "$sub_relative_path"
        echo "${indent}}"
    done
}

# Function to collect all texture paths
collect_all_textures() {
    local dir="$1"
    local relative_path="$2"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        echo "            \"$file_path\","
    done
    
    # Process subdirectories recursively
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        collect_all_textures "$subdir" "$sub_relative_path"
    done
}

# Function to generate Content.mgcb header
generate_mgcb_header() {
    cat << 'EOF'
# AUTOGENERATED FROM Scripts/generate-textures.sh

#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:DesktopGL
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

EOF
}

# Function to generate a single texture entry for Content.mgcb
generate_mgcb_texture_entry() {
    local texture_path="$1"
    cat << EOF
#begin img/$texture_path.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:img/$texture_path.png

EOF
}

# Function to generate all texture entries for Content.mgcb recursively
generate_mgcb_texture_entries() {
    local dir="$1"
    local relative_path="$2"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        generate_mgcb_texture_entry "$file_path"
    done
    
    # Process subdirectories recursively
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        generate_mgcb_texture_entries "$subdir" "$sub_relative_path"
    done
}

# Validate all files before generating
echo "Validating files in $sourceDirectory..."
if ! validate_all_files "$sourceDirectory"; then
    echo "Validation failed. Aborting generation." >&2
    exit 1
fi
echo "Validation passed."

# Generate the C# file
cat > "$txDestinationPath" << 'EOF'
// AUTOGENERATED FROM Scripts/generate-textures.sh

using System.Collections.Generic;

namespace AstroMiner.Definitions
{
    public static class Tx
    {
EOF

# Generate class content
generate_class_content "$sourceDirectory" "        " "" >> "$txDestinationPath"

# Generate AllTextures list
echo "" >> "$txDestinationPath"
echo "        public static readonly List<string> AllTextures = new List<string>" >> "$txDestinationPath"
echo "        {" >> "$txDestinationPath"
collect_all_textures "$sourceDirectory" "" >> "$txDestinationPath"
echo "        };" >> "$txDestinationPath"

# Close the class and namespace
cat >> "$txDestinationPath" << 'EOF'
    }
}
EOF

# Generate the Content.mgcb file
generate_mgcb_header > "$mgcbDestinationPath"
generate_mgcb_texture_entries "$sourceDirectory" "" >> "$mgcbDestinationPath"

echo "Generated $txDestinationPath"
echo "Generated $mgcbDestinationPath"