#!/bin/bash

# Generates AstroMiner/Definitions/Tx.cs with string constants for all PNG files in the Content/img directory.
# Also generates AstroMiner/Content/Content.mgcb with texture build configuration.
# Run from the project root: ./Scripts/generate-textures.sh

# Configuration
sourceDirectory="AstroMiner/Content/img"
txDestinationPath="AstroMiner/Definitions/Tx.cs"
mgcbDestinationPath="AstroMiner/Content/Content.mgcb"

# Function to convert filename to property name (remove extension)
to_property_name() {
    local filename="$1"
    echo "${filename%.*}"
}

# Function to generate class content recursively
generate_class_content() {
    local dir="$1"
    local indent="$2"
    local relative_path="$3"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        echo "${indent}public const string $property_name = \"$file_path\";"
    done
    
    # Process subdirectories
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        
        echo "${indent}public static class $dirname"
        echo "${indent}{"
        generate_class_content "$subdir" "$indent    " "$sub_relative_path"
        echo "${indent}}"
    done
}

# Function to collect all texture paths
collect_all_textures() {
    local dir="$1"
    local relative_path="$2"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        echo "            \"$file_path\","
    done
    
    # Process subdirectories recursively
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        collect_all_textures "$subdir" "$sub_relative_path"
    done
}

# Function to generate Content.mgcb header
generate_mgcb_header() {
    cat << 'EOF'
# AUTOGENERATED FROM Scripts/generate-textures.sh

#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:DesktopGL
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#


#---------------------------------- Content ---------------------------------#

EOF
}

# Function to generate a single texture entry for Content.mgcb
generate_mgcb_texture_entry() {
    local texture_path="$1"
    cat << EOF
#begin img/$texture_path.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:img/$texture_path.png

EOF
}

# Function to generate all texture entries for Content.mgcb recursively
generate_mgcb_texture_entries() {
    local dir="$1"
    local relative_path="$2"
    
    # Process PNG files in current directory
    for file in "$dir"/*.png; do
        [ -f "$file" ] || continue
        local filename=$(basename "$file")
        local property_name=$(to_property_name "$filename")
        local file_path="$relative_path$(to_property_name "$filename")"
        generate_mgcb_texture_entry "$file_path"
    done
    
    # Process subdirectories recursively
    for subdir in "$dir"/*/; do
        [ -d "$subdir" ] || continue
        local dirname=$(basename "$subdir")
        local sub_relative_path="$relative_path$dirname/"
        generate_mgcb_texture_entries "$subdir" "$sub_relative_path"
    done
}

# Generate the C# file
cat > "$txDestinationPath" << 'EOF'
// AUTOGENERATED FROM Scripts/generate-textures.sh
using System.Collections.Generic;

namespace AstroMiner.Definitions
{
    public static class Tx
    {
EOF

# Generate class content
generate_class_content "$sourceDirectory" "        " "" >> "$txDestinationPath"

# Generate AllTextures list
echo "" >> "$txDestinationPath"
echo "        public static readonly List<string> AllTextures = new List<string>" >> "$txDestinationPath"
echo "        {" >> "$txDestinationPath"
collect_all_textures "$sourceDirectory" "" >> "$txDestinationPath"
echo "        };" >> "$txDestinationPath"

# Close the class and namespace
cat >> "$txDestinationPath" << 'EOF'
    }
}
EOF

# Generate the Content.mgcb file
generate_mgcb_header > "$mgcbDestinationPath"
generate_mgcb_texture_entries "$sourceDirectory" "" >> "$mgcbDestinationPath"

echo "Generated $txDestinationPath"
echo "Generated $mgcbDestinationPath"